version: '3.8'

networks:
  loc-net:
    name: loc-net

services:
  orderer.loc.com:
    container_name: orderer.loc.com
    image: hyperledger/fabric-orderer:2.5
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    volumes:
      - ../organizations/ordererOrganizations/loc.com/orderers/orderer.loc.com/msp:/var/hyperledger/orderer/msp
      - ../organizations/ordererOrganizations/loc.com/orderers/orderer.loc.com/tls:/var/hyperledger/orderer/tls
      - orderer.loc.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
    networks:
      - loc-net

  # Additional services for peers (TataMotors, Tesla, ICICIBank, ChaseBank) would go here
  # Following the same pattern as above for each organization's peer
